[Portfolio:] Desktop Version: Add Layout and Style
IsraMarvin/Portfolio pull request #6
Opened 2021-12-11 10:47 UTC by IsraMarvin

Enhancement Done ♻️

➕ Use media queries to make the desktop version look like the template.
➕ Use grid and flexbox to layout the desktop version.

2021-12-11 11:25 UTC, Cathella requested changes
## Status: Changes Requested 🛑

### Hi @IsraMarvin 👋🏻, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] [REQUIRED] As mentioned by the previous reviewer [here](https://github.com/IsraMarvin/Portfolio/pull/4#discussion_r767045955), The about section in the left block is meant to take about 40% of the overall width, while the right block with the skills takes 60% as per project requirements. However, this is different in your design since it visually looks the other way round. I think it will really be nice if you corrected this aspect 😅.
- [ ] [REQUIRED] As seen [here](https://github.com/IsraMarvin/Portfolio/pull/4#discussion_r767052979), the previous reviewer mentioned that the mobile version of your portfolio should look as expected. This still does not reflect in your design because it still quite broken. This is a project requirement,  and I think it will really be nice if you take some time and effort to implement the required changes 🥺.


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-11 13:22 UTC, HENRYKC24 approved these changes
# STATUS: APPROVED, BUT CHANGES SUGGESTED :heavy_check_mark: 
## Hi @IsraMarvin :wave:, 

Your project is hereby approved! Please, consider making those changes suggested. They will greatly improve your UI. Great job:+1:
- [x]  [OPTIONAL] I suggest you fix some typos in your project. The collapse (>) buttons are too close to the edge of the page. Please, consider adjusting them a little. This will make your project look better, of course. Don't forget to remove the dot on `Skills.`
## Your Design:point_down:
![image](https://user-images.githubusercontent.com/45668340/145678107-92ac5817-e85a-4375-974e-01d53294f6c6.png)
## The template:point_down:
![image](https://user-images.githubusercontent.com/45668340/145678151-c413ad91-f72f-4821-a4ab-0d9f17bcd46e.png)

_**Check some inline comments I left under some lines of codes**_
## Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-11 13:22 UTC, HENRYKC24 commented on index.html
> +                    <div class="tonic-items">
- [ ] [OPTIONAL] Looking at the margin under the project name and the next line of text, I really think you should add some spaces between them. This will enhance your UI and get you closer to the design template.
## Your Design
![image](https://user-images.githubusercontent.com/45668340/145677453-94b7b84c-6009-439a-b4ef-91c9c6f93945.png)
## The Template
![image](https://user-images.githubusercontent.com/45668340/145677503-fbc52f81-5ee8-45b2-bfb3-161bdf90a806.png)

2021-12-11 13:23 UTC, merged

2021-12-15 15:46 UTC, HENRYKC24 reviewed
# STATUS: INVALID REVIEW REQUEST :negative_squared_cross_mark: 
## Hi @IsraMarvin:wave:, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a new pull request created for it. **Please, make sure you create a new pull request for this project and also a new branch.**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._